(require 'autothemer)
(autothemer-deftheme
 notebook-light "Light theme for code notebooks"
 (
  (((class color) (min-colors #xFFFFFF)))
  (main-bg "#ffffff")
  (tone1   "#e5e5e5") ; lightest
  (tone2   "#bbbbbb")
  (tone3   "#777777") ; darkest
  (main-fg "#000000")

  (purple  "#a71d5d")
  (orange  "#eb6a43")
  (red     "#CC342B")
  (green   "#198844")
  (yellow  "#fba922")
  (blue    "#183691")
  (light-magenta "#c8c8fa")
  (magenta "#795da3")
  (cyan    "#0086b3")
  )
 (
  (bold (:weight 'bold))
  (italic (:slant 'italic))
  (bold-italic (:weight 'bold :slant 'italic))
  (underline (:underline t))
  (default (:foreground main-fg :background main-bg))
  (mode-line
   (:box
    (:line-width 1 :style nil)
    :foreground main-fg :background tone2))
  (mode-line-inactive
   (:box
    (:line-width 1 :style nil)
    :foreground main-fg :background tone1))
  (cursor  (:foreground main-bg :background main-fg))

  (font-lock-comment-face (:foreground tone3))
  (font-lock-comment-delimiter-face (:inherit 'font-lock-comment-face))
  (font-lock-string-face (:foreground green))
  (font-lock-doc-face (:inherit 'font-lock-string-face))
  (font-lock-doc-markup-face (:inherit 'font-lock-constant-face))
  (font-lock-keyword-face (:foreground magenta :weight 'bold))
  (font-lock-builtin-face (:foreground purple))
  (font-lock-function-name-face (:foreground blue))
  (font-lock-variable-name-face (:foreground red))
  (font-lock-type-face (:foreground main-fg))
  (font-lock-constant-face (:foreground cyan))
  (font-lock-warning-face (:inherit 'error))
  (font-lock-negation-char-face nil)
  (font-lock-preprocessor-face (:inherit 'font-lock-builtin-face))
  (font-lock-regexp-grouping-backslash (:inherit 'bold))
  (font-lock-regexp-grouping-construct (:inherit 'bold))

  (outline-1 (:foreground blue))
  (outline-2 (:foreground magenta))
  (outline-3 (:foreground green))
  (outline-4 (:foreground cyan))
  (outline-5 (:foreground orange))
  (outline-6 (:foreground red))
  (outline-7 (:foreground blue))
  (outline-8 (:foreground blue))
  (shadow (:foreground tone3))
  (link (:underline t :foreground blue))
  (link-visited (:inherit 'link))
  (highlight (:background main-bg :foreground red))
  (region (:extend t :background tone2))
  (secondary-selection (:extend t :background main-bg))
  (hl-line (:background tone1))

  ;;; searching
  (isearch (:underline t :background light-magenta :foreground main-fg))
  (isearch-fail (:foreground main-fg))
  (lazy-highlight (:inherit 'isearch))
  (isearch-group-1 (:inherit 'isearch))
  (isearch-group-2 (:inherit 'isearch))
  (file-name-shadow (:inherit 'isearch))
  (query-replace (:foreground main-fg))
  (match (:inherit 'isearch))

  ;;; org
  (org-default (:inherit 'default))
  (org-hide (:foreground main-bg))
  (org-dispatcher-highlight (:weight 'bold :foreground main-fg :background main-bg))
  (org-level-1 (:inherit 'outline-1 :underline t))
  (org-level-2 (:inherit 'outline-2 :underline t))
  (org-level-3 (:inherit 'outline-3 :underline t))
  (org-level-4 (:inherit 'outline-4 :underline t))
  (org-level-5 (:inherit 'outline-5 :underline t))
  (org-level-6 (:inherit 'outline-6 :underline t))
  (org-level-7 (:inherit 'outline-7 :underline t))
  (org-level-8 (:inherit 'outline-8 :underline t))
  (org-special-keyword (:inherit 'font-lock-keyword-face))
  (org-drawer (:inherit 'shadow))
  (org-property-value nil)
  (org-column (:weight 'normal :slant 'normal :underline nil :strike-through nil :background main-bg))
  (org-column-title (:weight 'bold :underline t :background main-bg))
  (org-agenda-column-dateline (:inherit 'org-column))
  (org-warning (:inherit 'font-lock-warning-face))
  (org-archived (:inherit 'shadow))
  (org-cite (:inherit 'link))
  (org-cite-key (:inherit 'link))
  (org-link (:inherit 'link))
  (org-footnote (:underline t :foreground main-fg))
  (org-ellipsis (:underline nil :foreground nil))
  (org-target (:underline t))
  (org-date (:underline nil :foreground blue))
  (org-date-selected (:inverse-video t :foreground main-fg))
  (org-sexp-date (:foreground main-fg))
  (org-tag (:weight 'bold))
  (org-list-dt (:weight 'bold))
  (org-todo (:weight 'bold :foreground main-fg))
  (org-done (:weight 'bold :foreground main-fg))
  (org-agenda-done (:foreground main-fg))
  (org-headline-todo (:foreground main-fg))
  (org-headline-done (:foreground main-fg))
  (org-priority (:inherit 'font-lock-keyword-face))
  (org-checkbox (:inherit 'bold))
  (org-checkbox-statistics-todo (:inherit 'org-todo))
  (org-checkbox-statistics-done (:inherit 'org-done))
  (org-table (:foreground main-fg))
  (org-table-header (:foreground main-fg :background main-bg :inherit 'org-table))
  (org-formula (:foreground main-fg))
  (org-code (:inherit 'shadow))
  (org-meta-line (:inherit 'font-lock-comment-face))
  (org-document-title (:foreground purple))
  (org-document-info (:foreground green))
  (org-document-info-keyword (:inherit 'shadow))
  (org-block (:extend t :foreground main-fg))
  (org-block-begin-line (:extend t :inherit 'org-meta-line))
  (org-block-end-line (:extend t :inherit 'org-block-begin-line))
  (org-verbatim (:foreground orange))
  (org-quote (:inherit 'org-block))
  (org-verse (:inherit 'org-block))
  (org-clock-overlay (:foreground main-fg :background main-bg))
  (org-agenda-structure (:foreground main-fg))
  (org-agenda-structure-secondary (:inherit 'org-agenda-structure))
  (org-agenda-structure-filter (:inherit ('org-warning 'org-agenda-structure)))
  (org-agenda-date (:inherit 'org-agenda-structure))
  (org-agenda-date-today (:weight 'bold :slant 'italic :inherit 'org-agenda-date))
  (org-agenda-date-weekend-today (:inherit 'org-agenda-date-today))
  (org-agenda-clocking (:inherit 'secondary-selection))
  (org-agenda-date-weekend (:weight 'bold :inherit 'org-agenda-date))
  (org-scheduled (:foreground main-fg))
  (org-scheduled-today (:foreground main-fg))
  (org-agenda-dimmed-todo-face (:foreground main-fg))
  (org-scheduled-previously (:foreground main-fg))
  (org-imminent-deadline (:inherit 'org-warning))
  (org-upcoming-deadline (:foreground main-fg))
  (org-upcoming-distant-deadline (:inherit 'org-default))
  (org-agenda-restriction-lock (:background main-bg))
  (org-agenda-filter-tags (:inherit 'mode-line))
  (org-agenda-filter-category (:inherit 'mode-line))
  (org-agenda-filter-effort (:inherit 'mode-line))
  (org-agenda-filter-regexp (:inherit 'mode-line))
  (org-time-grid (:foreground main-fg))
  (org-agenda-current-time (:inherit 'org-time-grid))
  (org-agenda-diary (:inherit 'default))
  (org-agenda-calendar-event (:inherit 'default))
  (org-agenda-calendar-sexp (:inherit 'default))
  (org-latex-and-related (:foreground main-fg))
  (org-macro (:inherit 'org-latex-and-related))
  (org-tag-group (:inherit 'org-tag))
  (org-mode-line-clock (:inherit 'mode-line))
  (org-mode-line-clock-overrun (:background main-bg :inherit 'mode-line))
  (org-indent (:foreground main-bg))

  ;;; main
  (trailing-whitespace (:foreground main-fg))
  (line-number (:inherit 'shadow))
  (line-number-current-line (:foreground main-fg))
  (line-number-major-tick (:foreground main-fg))
  (line-number-minor-tick (:foreground main-fg))
  (fill-column-indicator (:foreground main-fg))
  (escape-glyph (:foreground main-fg))
  (homoglyph (:foreground main-fg))
  (nobreak-space (:foreground main-fg))
  (nobreak-hyphen (:foreground main-fg))
  (mode-line-highlight (:foreground main-fg))
  (mode-line-emphasis (:foreground main-fg))
  (mode-line-buffer-id (:foreground main-fg))
  (header-line (:foreground main-fg))
  (header-line-highlight (:foreground main-fg))
  (vertical-border (:foreground main-fg))
  (window-divider (:foreground main-fg))
  (window-divider-first-pixel (:foreground main-fg))
  (window-divider-last-pixel (:foreground main-fg))
  (internal-border (:foreground main-fg))
  (child-frame-border (:foreground main-fg))
  (minibuffer-prompt (:foreground main-fg))
  (fringe (:foreground main-fg))
  (scroll-bar (:foreground main-fg))
  (border (:foreground main-fg))
  (mouse (:foreground main-fg))
  (tool-bar (:foreground main-fg))
  (tab-bar (:foreground main-fg))
  (tab-line (:foreground main-fg))
  (menu (:foreground main-fg))
  (help-argument-name (:foreground main-fg))
  (help-key-binding (:foreground main-fg))
  (glyphless-char (:foreground main-fg))
  (error (:foreground red))
  (warning (:foreground main-fg))
  (success (:foreground main-fg))
  (read-multiple-choice-face (:foreground main-fg))
  (tty-menu-enabled-face (:foreground main-fg))
  (tty-menu-disabled-face (:foreground main-fg))
  (tty-menu-selected-face (:foreground main-fg))
  (show-paren-match (:foreground purple))
  (show-paren-match-expression (:foreground main-fg))
  (show-paren-mismatch (:foreground main-fg))
  (button (:foreground main-fg))
  (next-error (:foreground red))
  (next-error-message (:foreground main-fg))
  (separator-line (:foreground main-fg))
  (help-for-help-header (:foreground main-fg))
  (completions-group-title (:foreground main-fg))
  (completions-group-separator (:foreground main-fg))
  (completions-annotations (:foreground main-fg))
  (completions-first-difference (:foreground main-fg))
  (completions-common-part (:foreground main-fg))
  (mouse-drag-and-drop-region (:foreground main-fg))
  (tabulated-list-fake-header (:foreground main-fg))
  (buffer-menu-buffer (:foreground main-fg))
  (vc-state-base (:foreground main-fg))
  (vc-up-to-date-state (:foreground main-fg))
  (vc-needs-update-state (:foreground main-fg))
  (vc-locked-state (:foreground main-fg))
  (vc-locally-added-state (:foreground main-fg))
  (vc-conflict-state (:foreground main-fg))
  (vc-removed-state (:foreground main-fg))
  (vc-missing-state (:foreground main-fg))
  (vc-edited-state (:foreground main-fg))
  (elisp-shorthand-font-lock-face (:foreground main-fg))
  (eldoc-highlight-function-argument (:foreground main-fg))
  (tooltip (:foreground main-fg))
  (browse-url-button (:foreground main-fg))
  (package-help-section-name (:foreground main-fg))
  (package-name (:foreground main-fg))
  (package-description (:foreground main-fg))
  (package-status-built-in (:foreground main-fg))
  (package-status-external (:foreground main-fg))
  (package-status-available (:foreground main-fg))
  (package-status-new (:foreground main-fg))
  (package-status-held (:foreground main-fg))
  (package-status-disabled (:foreground main-fg))
  (package-status-installed (:foreground main-fg))
  (package-status-dependency (:foreground main-fg))
  (package-status-unsigned (:foreground main-fg))
  (package-status-incompat (:foreground main-fg))
  (package-status-avail-obso (:foreground main-fg))
  (info-node (:foreground main-fg))
  (info-title-1 (:foreground main-fg))
  (info-title-2 (:foreground main-fg))
  (info-title-3 (:foreground main-fg))
  (info-title-4 (:foreground main-fg))
  (info-menu-header (:foreground main-fg))
  (info-menu-star (:foreground main-fg))
  (info-xref (:foreground main-fg))
  (info-xref-visited (:foreground main-fg))
  (info-header-xref (:foreground main-fg))
  (info-header-node (:foreground main-fg))
  (info-index-match (:foreground main-fg))
  (Info-quoted (:foreground main-fg))
  (calendar-today (:foreground main-fg))
  (diary (:foreground main-fg))
  (holiday (:foreground main-fg))
  (calendar-weekday-header (:foreground main-fg))
  (calendar-weekend-header (:foreground main-fg))
  (calendar-month-header (:foreground main-fg))
  (ansi-color-bold (:foreground main-fg))
  (ansi-color-faint (:foreground main-fg))
  (ansi-color-italic (:foreground main-fg))
  (ansi-color-underline (:foreground main-fg))
  (ansi-color-slow-blink (:foreground main-fg))
  (ansi-color-fast-blink (:foreground main-fg))
  (ansi-color-inverse (:foreground main-fg))
  (ansi-color-black (:foreground main-fg))
  (ansi-color-red (:foreground main-fg))
  (ansi-color-green (:foreground main-fg))
  (ansi-color-yellow (:foreground main-fg))
  (ansi-color-blue (:foreground main-fg))
  (ansi-color-magenta (:foreground main-fg))
  (ansi-color-cyan (:foreground main-fg))
  (ansi-color-white (:foreground main-fg))
  (ansi-color-bright-black (:foreground main-fg))
  (ansi-color-bright-red (:foreground main-fg))
  (ansi-color-bright-green (:foreground main-fg))
  (ansi-color-bright-yellow (:foreground main-fg))
  (ansi-color-bright-blue (:foreground main-fg))
  (ansi-color-bright-magenta (:foreground main-fg))
  (ansi-color-bright-cyan (:foreground main-fg))
  (ansi-color-bright-white (:foreground main-fg))
  (comint-highlight-input (:foreground main-fg))
  (comint-highlight-prompt (:foreground main-fg))
  (dired-header (:foreground main-fg))
  (dired-mark (:foreground main-fg))
  (dired-marked (:foreground main-fg))
  (dired-flagged (:foreground main-fg))
  (dired-warning (:foreground main-fg))
  (dired-perm-write (:foreground main-fg))
  (dired-set-id (:foreground main-fg))
  (dired-directory (:foreground main-fg))
  (dired-symlink (:foreground main-fg))
  (dired-broken-symlink (:foreground main-fg))
  (dired-special (:foreground main-fg))
  (dired-ignored (:foreground main-fg))
  (widget-documentation (:foreground main-fg))
  (widget-button (:foreground main-fg))
  (widget-field (:foreground main-fg))
  (widget-single-line-field (:foreground main-fg))
  (widget-inactive (:foreground main-fg))
  (widget-button-pressed (:foreground main-fg))
  (rmail-highlight (:foreground main-fg))
  (rmail-header-name (:foreground main-fg))
  (gnus-group-news-1-empty (:foreground main-fg))
  (gnus-group-news-1 (:foreground main-fg))
  (gnus-group-news-2-empty (:foreground main-fg))
  (gnus-group-news-2 (:foreground main-fg))
  (gnus-group-news-3-empty (:foreground main-fg))
  (gnus-group-news-3 (:foreground main-fg))
  (gnus-group-news-4-empty (:foreground main-fg))
  (gnus-group-news-4 (:foreground main-fg))
  (gnus-group-news-5-empty (:foreground main-fg))
  (gnus-group-news-5 (:foreground main-fg))
  (gnus-group-news-6-empty (:foreground main-fg))
  (gnus-group-news-6 (:foreground main-fg))
  (gnus-group-news-low-empty (:foreground main-fg))
  (gnus-group-news-low (:foreground main-fg))
  (gnus-group-mail-1-empty (:foreground main-fg))
  (gnus-group-mail-1 (:foreground main-fg))
  (gnus-group-mail-2-empty (:foreground main-fg))
  (gnus-group-mail-2 (:foreground main-fg))
  (gnus-group-mail-3-empty (:foreground main-fg))
  (gnus-group-mail-3 (:foreground main-fg))
  (gnus-group-mail-low-empty (:foreground main-fg))
  (gnus-group-mail-low (:foreground main-fg))
  (gnus-summary-selected (:foreground main-fg))
  (gnus-summary-cancelled (:foreground main-fg))
  (gnus-summary-normal-ticked (:foreground main-fg))
  (gnus-summary-high-ticked (:foreground main-fg))
  (gnus-summary-low-ticked (:foreground main-fg))
  (gnus-summary-normal-ancient (:foreground main-fg))
  (gnus-summary-high-ancient (:foreground main-fg))
  (gnus-summary-low-ancient (:foreground main-fg))
  (gnus-summary-normal-undownloaded (:foreground main-fg))
  (gnus-summary-high-undownloaded (:foreground main-fg))
  (gnus-summary-low-undownloaded (:foreground main-fg))
  (gnus-summary-normal-unread (:foreground main-fg))
  (gnus-summary-high-unread (:foreground main-fg))
  (gnus-summary-low-unread (:foreground main-fg))
  (gnus-summary-normal-read (:foreground main-fg))
  (gnus-summary-high-read (:foreground main-fg))
  (gnus-summary-low-read (:foreground main-fg))
  (gnus-splash (:foreground main-fg))
  (mm-command-output (:foreground main-fg))
  (epa-validity-high (:foreground main-fg))
  (epa-validity-medium (:foreground main-fg))
  (epa-validity-low (:foreground main-fg))
  (epa-validity-disabled (:foreground main-fg))
  (epa-string (:foreground main-fg))
  (epa-mark (:foreground main-fg))
  (epa-field-name (:foreground main-fg))
  (epa-field-body (:foreground main-fg))
  (message-header-to (:foreground main-fg))
  (message-header-cc (:foreground main-fg))
  (message-header-subject (:foreground main-fg))
  (message-header-newsgroups (:foreground main-fg))
  (message-header-other (:foreground main-fg))
  (message-header-name (:foreground main-fg))
  (message-header-xheader (:foreground main-fg))
  (message-separator (:foreground main-fg))
  (message-cited-text-1 (:foreground main-fg))
  (message-cited-text-2 (:foreground main-fg))
  (message-cited-text-3 (:foreground main-fg))
  (message-cited-text-4 (:foreground main-fg))
  (message-mml (:foreground main-fg))
  (message-signature-separator (:foreground main-fg))
  (shr-strike-through (:foreground main-fg))
  (shr-link (:foreground main-fg))
  (shr-selected-link (:foreground main-fg))
  (shr-abbreviation (:foreground main-fg))
  (shr-h1 (:foreground main-fg))
  (shr-h2 (:foreground main-fg))
  (shr-h3 (:foreground main-fg))
  (shr-h4 (:foreground main-fg))
  (shr-h5 (:foreground main-fg))
  (shr-h6 (:foreground main-fg))
  (mm-uu-extract (:foreground main-fg))
  (gnus-emphasis-bold (:foreground main-fg))
  (gnus-emphasis-italic (:foreground main-fg))
  (gnus-emphasis-underline (:foreground main-fg))
  (gnus-emphasis-underline-bold (:foreground main-fg))
  (gnus-emphasis-underline-italic (:foreground main-fg))
  (gnus-emphasis-bold-italic (:foreground main-fg))
  (gnus-emphasis-underline-bold-italic (:foreground main-fg))
  (gnus-emphasis-strikethru (:foreground main-fg))
  (gnus-emphasis-highlight-words (:foreground main-fg))
  (gnus-button (:foreground main-fg))
  (gnus-signature (:foreground main-fg))
  (gnus-header-from (:foreground main-fg))
  (gnus-header-subject (:foreground main-fg))
  (gnus-header-newsgroups (:foreground main-fg))
  (gnus-header-name (:foreground main-fg))
  (gnus-header-content (:foreground main-fg))
  (speedbar-button-face (:foreground main-fg))
  (speedbar-file-face (:foreground main-fg))
  (speedbar-directory-face (:foreground main-fg))
  (speedbar-tag-face (:foreground main-fg))
  (speedbar-selected-face (:foreground main-fg))
  (speedbar-highlight-face (:foreground main-fg))
  (speedbar-separator-face (:foreground main-fg))
  (diff-header (:foreground main-fg))
  (diff-file-header (:foreground main-fg))
  (diff-index (:foreground main-fg))
  (diff-hunk-header (:foreground main-fg))
  (diff-removed (:foreground main-fg))
  (diff-added (:foreground main-fg))
  (diff-changed-unspecified (:foreground main-fg))
  (diff-changed (:foreground main-fg))
  (diff-indicator-removed (:foreground main-fg))
  (diff-indicator-added (:foreground main-fg))
  (diff-indicator-changed (:foreground main-fg))
  (diff-function (:foreground main-fg))
  (diff-context (:foreground main-fg))
  (diff-nonexistent (:foreground main-fg))
  (diff-error (:foreground main-fg))
  (diff-refine-changed (:foreground main-fg))
  (diff-refine-removed (:foreground main-fg))
  (diff-refine-added (:foreground main-fg))

  (ivy-cursor (:foreground main-fg))
  (ivy-current-match (:foreground main-fg :background tone1))
  (ivy-minibuffer-match-highlight (:foreground main-fg :background tone1))
  (ivy-minibuffer-match-face-1 (:foreground main-fg))
  (ivy-minibuffer-match-face-2 (:foreground main-fg))
  (ivy-minibuffer-match-face-3 (:foreground main-fg))
  (ivy-minibuffer-match-face-4 (:foreground main-fg))
  (ivy-confirm-face (:foreground main-fg))
  (ivy-match-required-face (:foreground main-fg))
  (ivy-subdir (:foreground main-fg))
  (ivy-org (:foreground main-fg))
  (ivy-modified-buffer (:foreground main-fg))
  (ivy-modified-outside-buffer (:foreground main-fg))
  (ivy-remote (:foreground main-fg))
  (ivy-virtual (:foreground main-fg))
  (ivy-action (:foreground main-fg))
  (ivy-highlight-face (:foreground main-fg))
  (ivy-prompt-match (:foreground main-fg))
  (ivy-separator (:foreground main-fg))
  (ivy-grep-info (:foreground main-fg))
  (ivy-grep-line-number (:foreground main-fg))
  (ivy-completions-annotations (:foreground main-fg))
  (ivy-yanked-word (:foreground main-fg))

  (swiper-match-face-1 (:foreground main-fg))
  (swiper-match-face-2 (:foreground main-fg))
  (swiper-match-face-3 (:foreground main-fg))
  (swiper-match-face-4 (:foreground main-fg))
  (swiper-background-match-face-1 (:foreground main-fg))
  (swiper-background-match-face-2 (:foreground main-fg))
  (swiper-background-match-face-3 (:foreground main-fg))
  (swiper-background-match-face-4 (:foreground main-fg))
  (swiper-line-face (:inherit 'isearch))

  (compilation-error (:foreground main-fg))
  (compilation-warning (:foreground main-fg))
  (compilation-info (:foreground main-fg))
  (compilation-mode-line-fail (:foreground main-fg))
  (compilation-mode-line-run (:foreground main-fg))
  (compilation-mode-line-exit (:foreground main-fg))
  (compilation-line-number (:foreground main-fg))
  (compilation-column-number (:foreground main-fg))
  (xref-file-header (:foreground main-fg))
  (xref-line-number (:foreground main-fg))
  (xref-match (:foreground main-fg))

  (counsel-variable-documentation (:foreground main-fg))
  (counsel-key-binding (:foreground main-fg))
  (counsel-active-mode (:foreground main-fg))
  (counsel--mark-ring-highlight (:foreground main-fg))
  (counsel-evil-register-face (:foreground main-fg))
  (counsel-application-name (:foreground main-fg))
  (counsel-outline-1 (:foreground main-fg))
  (counsel-outline-2 (:foreground main-fg))
  (counsel-outline-3 (:foreground main-fg))
  (counsel-outline-4 (:foreground main-fg))
  (counsel-outline-5 (:foreground main-fg))
  (counsel-outline-6 (:foreground main-fg))
  (counsel-outline-7 (:foreground main-fg))
  (counsel-outline-8 (:foreground main-fg))
  (counsel-outline-default (:foreground main-fg))

  (ibuffer-locked-buffer (:foreground main-fg))
  (ffap (:foreground main-fg))
  (dashboard-text-banner (:foreground main-fg))
  (dashboard-banner-logo-title (:foreground main-fg))
  (dashboard-navigator (:foreground main-fg))
  (dashboard-heading (:foreground main-fg))
  (dashboard-items-face (:foreground main-fg))
  (dashboard-no-items-face (:foreground main-fg))
  (dashboard-footer (:inherit 'shadow :slant 'italic))
  (evil-ex-commands (:foreground main-fg))
  (evil-ex-info (:foreground main-fg))
  (evil-ex-search (:foreground main-fg))
  (evil-ex-lazy-highlight (:foreground main-fg))
  (evil-ex-substitute-matches (:foreground main-fg))
  (evil-ex-substitute-replacement (:foreground main-fg))
  (rectangle-preview (:foreground main-fg))
  (calc-nonselected-face (:foreground main-fg))
  (calc-selected-face (:foreground main-fg))
  (which-key-key-face (:foreground main-fg))
  (which-key-separator-face (:foreground main-fg))
  (which-key-note-face (:foreground main-fg))
  (which-key-command-description-face (:foreground main-fg))
  (which-key-local-map-description-face (:foreground main-fg))
  (which-key-highlighted-command-face (:foreground main-fg))
  (which-key-group-description-face (:foreground main-fg))
  (which-key-special-key-face (:foreground main-fg))
  (which-key-docstring-face (:foreground main-fg))
  (sp-pair-overlay-face (:foreground main-fg))
  (sp-wrap-overlay-face (:foreground main-fg))
  (sp-wrap-overlay-opening-pair (:foreground main-fg))
  (sp-wrap-overlay-closing-pair (:foreground main-fg))
  (sp-wrap-tag-overlay-face (:foreground main-fg))
  (sp-show-pair-match-face (:foreground main-fg))
  (sp-show-pair-mismatch-face (:foreground main-fg))
  (sp-show-pair-enclosing (:foreground main-fg))
  (sp-show-pair-match-content-face (:foreground main-fg))
  (yas-field-highlight-face (:foreground main-fg))
  (yas--field-debug-face (:foreground main-fg))
  (table-cell (:foreground main-fg))
  (world-clock-label (:foreground main-fg))
  (shortdoc-heading (:foreground main-fg))
  (shortdoc-section (:foreground main-fg))
  )
 )

(provide-theme 'notebook-light)
